PUPIL-587 Feat/oak pupil journey layout
oaknational/oak-components pull request #145
Opened 2024-04-12 10:19 UTC by benprotheroe

# How to review this PR

_Leave this text block for the reviewer_

- Check [component hierarchy](https://miro.com/app/board/uXjVNnKBgyk=/?share_link_id=59445593794) is followed correctly
- Check the design [Heuristics](https://components.thenational.academy/?path=/docs/docs-howtodesigncomponents--docs#heuristics-for-component-design) have been followed
- Check [naming conventions](https://components.thenational.academy/?path=/docs/docs-namingconventions--docs) have been applied
- Check for these gotchyas:
  - Missing exports for Oak components
  - Accidental export of Internal components
  - Snapshots of unexpected components have been modified
  - Circular dependencies
  - Code duplication (via not using base components)
  - Non-functional storybook for this or related components
  - Sensitve files changed eg. atoms, or style tokens
  - Relative imports
  - Default exports

# Add your PR description below

PupilJourneyLayout componets

use case: tiers (programme factors), unit, lesson listing

The different sections are passed in as children and props

## Link to the design doc

https://www.figma.com/file/zqpeecgzMGKRli2gUdJOLp/Pupil-Browse?type=design&node-id=4261%3A38021&mode=dev

## A link to the component in the deployment preview

## Testing instructions

You can view the component using the above link in storybook

test for phases, pages

## ACs

2024-04-12 11:02 UTC, messmike commented
@benprotheroe looking good, just need to update the height for tablet and mobile breakpoints for the backlink container if possible, e.g:
![Screenshot 2024-04-12 at 12 02 21 pm](https://github.com/oaknational/oak-components/assets/67056434/12020c82-6a65-4537-9fcc-ec3df6a18421)
![Screenshot 2024-04-12 at 12 01 55 pm](https://github.com/oaknational/oak-components/assets/67056434/28359ee4-71e6-4e30-8f1c-ac7af5a4b7e9)

2024-04-12 11:51 UTC, RBrownsett commented
Nice @benprotheroe . Just a couple of things from me:

- The button that takes users back to the previous page seems to be hardcoded with 'View all units' for every section - will this be updated to reflect the correct text (e.g. tier-listing section would display 'Select subject' and unit-listing would display 'Select tier'
![image](https://github.com/oaknational/oak-components/assets/30384846/82190864-1d08-4aaa-9929-180c4e0724f4)

- Do we need to add any unit or snapshot tests? Noticed we had some in the previous PR so wondered if this was standard practice :-)

2024-04-12 11:56 UTC, messmike approved these changes

2024-04-16 11:04 UTC, kimon-satan requested changes

2024-04-16 11:04 UTC, kimon-satan commented on src/components/organisms/pupil/OakPupilJourneyLayout/OakPupilJourneyLayout.tsx
> +        {children}
In relation to the problem we discussed earlier about margin: If children was in the above flex box all would be resolved.

2024-04-17 10:48 UTC, benprotheroe commented on src/components/organisms/pupil/OakPupilJourneyLayout/OakPupilJourneyLayout.tsx
> + * `OakBox` does not support space-between tokens on `padding` only `margin`, so we need to
removed

2024-04-17 11:02 UTC, kimon-satan approved these changes

2024-04-17 11:03 UTC, merged