Feat/pupil 886/expandable quiz review item
oaknational/oak-components pull request #247
Opened 2024-07-26 12:52 UTC by benprotheroe

# How to review this PR

_Leave this text block for the reviewer_

- Check [component hierarchy](https://miro.com/app/board/uXjVNnKBgyk=/?share_link_id=59445593794) is followed correctly
- Check the design [Heuristics](https://components.thenational.academy/?path=/docs/docs-howtodesigncomponents--docs#heuristics-for-component-design) have been followed
- Check [naming conventions](https://components.thenational.academy/?path=/docs/docs-namingconventions--docs) have been applied
- Check for these gotchyas:
  - Missing exports for Oak components
  - Accidental export of Internal components
  - Snapshots of unexpected components have been modified
  - Circular dependencies
  - Code duplication (via not using base components)
  - Non-functional storybook for this or related components
  - Sensitve files changed eg. atoms, or style tokens
  - Relative imports
  - Default exports

# Add your PR description below

When I render a review item for quizzes,
I want to be able to nest extra information
So that I can render full quiz results.

## Link to the design doc
https://www.figma.com/design/G7z5ufo2T0CHk14CkadeuB/Pupil-Lesson?node-id=9597-174075&m=dev

## A link to the component in the deployment preview

## Testing instructions

## ACs

- [ ]  The item has a toggle button to expand
- [ ]  It expands with an area that can be populated by composition
- [ ]  mobile, tablet and desktop views
- [ ]  accessible

2024-07-29 08:42 UTC, messmike commented
- For desktop, can we position the score to the right of the title, so that the button is the only item on the right-hand side: 
![Screenshot 2024-07-29 at 9 34 47 am](https://github.com/user-attachments/assets/3b7391d5-cd23-44d6-baad-bf1cdc245891)

- When expanded the space between the expanded white space and the items above is missing space (should be `space-between-m`): 
![Screenshot 2024-07-29 at 9 40 09 am](https://github.com/user-attachments/assets/f51b7646-cc8b-4f20-9ff0-5c8ed7e4991c)

- The chevron icon spins 360 when clicked/tapped. When the accordion is expanded the chevron icon should point up: 
![Screenshot 2024-07-29 at 9 38 33 am](https://github.com/user-attachments/assets/9ced9a41-a705-4fd0-a0d6-bb6edd6bc218)

2024-07-29 10:04 UTC, kimon-satan requested changes
minor change to the header prop name

2024-07-29 12:30 UTC, benprotheroe commented on src/components/organisms/pupil/OakLessonReviewItem/OakPupilLessonReviewItem.tsx
> +      <OakFlex $gap="space-between-m" $alignItems="center" $width={"100%"}>
if you want to see how it works look at the code for the expandableReview component and the reviewItem components stories

2024-07-29 12:32 UTC, messmike approved these changes

2024-07-29 13:02 UTC, kimon-satan approved these changes

2024-07-29 13:58 UTC, RBrownsett commented
@benprotheroe accessibility issue fixed - not sure if its a storybook quirk but when in small mobile view the quiz background does not span behind the text? 

![image](https://github.com/user-attachments/assets/ff239475-4283-40cf-9c50-1a1c312f156f)

2024-07-30 15:01 UTC, benprotheroe commented
> @benprotheroe accessibility issue fixed - not sure if its a storybook quirk but when in small mobile view the quiz background does not span behind the text?
> 
> ![image](https://private-user-images.githubusercontent.com/30384846/353102398-ff239475-4283-40cf-9c50-1a1c312f156f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNDk4OTIsIm5iZiI6MTcyMjM0OTU5MiwicGF0aCI6Ii8zMDM4NDg0Ni8zNTMxMDIzOTgtZmYyMzk0NzUtNDI4My00MGNmLTljNTAtMWExYzMxMmYxNTZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDE0MjYzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3NDFkNTAxNGNjZWNhNDFiMGI0MjllNDc3ODQ5MTE0ZDIxMzMwNThkZjhhYjIzMzBkYzg2ZDAwOTAzYmVlZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JYnpQ8o3yKUgOmEkpGuHrktNAOLH8RjC7Nf1AgZRxZM)

i think this is a storybook quirk

2024-07-30 15:28 UTC, RBrownsett commented
@benprotheroe noticed that in tablet mode the score is aligned to the left - on the design its to the right

![image](https://github.com/user-attachments/assets/f74fe925-fcbe-4695-9b29-bca09840aeec)

2024-07-30 16:11 UTC, benprotheroe commented
> @benprotheroe noticed that in tablet mode the score is aligned to the left - on the design its to the right
> 
> ![image](https://private-user-images.githubusercontent.com/30384846/353520617-f74fe925-fcbe-4695-9b29-bca09840aeec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNTYxNTIsIm5iZiI6MTcyMjM1NTg1MiwicGF0aCI6Ii8zMDM4NDg0Ni8zNTM1MjA2MTctZjc0ZmU5MjUtZmNiZS00Njk1LTliMjktYmNhMDk4NDBhZWVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDE2MTA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxODc4YjQ5NGJlYWIzZWYzNDVkODY3NmYyNzBkOGE1NTgzODI3NDRlZTM5ZjIzMjUzZjQ1MzgzMmYyYWJkZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q_Q8a6gosHTtiOhyFqJKmg-RI108cD1GhyhNGlGV_Zc)

yep, fixed

2024-07-31 08:44 UTC, kimon-satan approved these changes
nice one

2024-07-31 09:30 UTC, merged