Feat add expired counts to unit cards
oaknational/oak-components pull request #267
Opened 2024-08-06 10:55 UTC by JBR90

# How to review this PR

_Leave this text block for the reviewer_

- Check [component hierarchy](https://miro.com/app/board/uXjVNnKBgyk=/?share_link_id=59445593794) is followed correctly
- Check the design [Heuristics](https://components.thenational.academy/?path=/docs/docs-howtodesigncomponents--docs#heuristics-for-component-design) have been followed
- Check [naming conventions](https://components.thenational.academy/?path=/docs/docs-namingconventions--docs) have been applied
- Check for these gotchyas:
  - Missing exports for Oak components
  - Accidental export of Internal components
  - Snapshots of unexpected components have been modified
  - Circular dependencies
  - Code duplication (via not using base components)
  - Non-functional storybook for this or related components
  - Sensitve files changed eg. atoms, or style tokens
  - Relative imports
  - Default exports

# Add your PR description below

-Fixes heading tag on container 
-Added expired lesson count

## Link to the design doc

## A link to the component in the deployment preview

## Testing instructions

## ACs

2024-08-06 16:29 UTC, RBrownsett approved these changes
Approved - heading and tabindex accessibility issue fixed

2024-08-06 17:04 UTC, k-huggs requested changes

2024-08-06 18:02 UTC, JBR90 commented on src/components/organisms/teacher/OakUnitListItem/OakUnitListItem.tsx
> +    if (expiredLessonCount && expiredLessonCount > lessonCount) {
To check is not null and it's greater than lesson count.

2024-08-07 07:19 UTC, k-huggs commented on src/components/organisms/teacher/OakUnitListItem/OakUnitListItem.tsx
> +    if (expiredLessonCount && expiredLessonCount > lessonCount) {
Apologies tired review yest evening

2024-08-07 07:19 UTC, JBR90 commented on src/components/organisms/teacher/OakUnitListItem/OakUnitListItem.tsx
> +    if (expiredLessonCount && expiredLessonCount > lessonCount) {
No worries

2024-08-07 07:34 UTC, k-huggs approved these changes

2024-08-07 07:34 UTC, k-huggs approved these changes

2024-08-07 07:34 UTC, merged