chore(deps): next 14 update
oaknational/oak-components pull request #54
Opened 2024-01-09 17:04 UTC by johnrobeds

Alignment to OWA packages to allow for Next 14 testing

2024-01-09 17:22 UTC, jimCresswell approved these changes

2024-01-09 17:48 UTC, kimon-satan requested changes
Cheers for doing this. Before merging the build needs to be tested against a version of OWA which uses next 14 before publishing or else it will block pupil squad's work. This can be done using yalc (see publish:local in package.json)

2024-01-09 17:48 UTC, kimon-satan commented on package.json
> +  "version": "0.0.20",
This will automatically increment on publish so shouldn't be changed here.

2024-01-10 09:22 UTC, jimCresswell commented
> Cheers for doing this. Before merging the build needs to be tested against a version of OWA which uses next 14 before publishing or else it will block pupil squad's work. This can be done using yalc (see publish:local in package.json)

@kimon-satan @johnrobeds are we satisfied this has been tested now?

2024-01-10 11:44 UTC, kimon-satan approved these changes

2024-01-10 11:46 UTC, merged