PUPIL-292- feat(pupil-lesson-review-item): create review item and add to storybook
oaknational/oak-components pull request #89
Opened 2024-01-29 15:18 UTC by benprotheroe

create OakLessonReviewItem component and add to strybook

the component is to be used in the pupil view lesson review page

2024-01-29 15:34 UTC, rightsaidjames commented
@benprotheroe Can you add a how to test section, screenshots etc.?

2024-01-29 15:41 UTC, messmike approved these changes

2024-01-29 16:06 UTC, kimon-satan requested changes
I made a few code style suggestions but otherwise all good.

2024-01-29 16:06 UTC, kimon-satan commented on src/components/integrated/OakLessonReviewItem/OakPupilLessonReviewItem.tsx
> +  switch (props.completed) {
Small code style thing, but while switch is the best option for when there are multiple conditions it doesn't make sense for something as simple as this. Here I would use a simple if and return early. Then follow up with the else condition (although no need to actually use the else keyword)

2024-01-29 16:06 UTC, kimon-satan commented on src/components/integrated/OakLessonReviewItem/OakPupilLessonReviewItem.tsx
> +function pickIconForSection(sectionName: LessonSectionName): OakIconName {
Again small style thing - It's nice to separate these things out but a function feels like over kill here. How about using a Map instead ?

2024-01-29 16:06 UTC, kimon-satan commented on src/components/integrated/OakLessonReviewItem/OakPupilLessonReviewItem.tsx
> +function renderQuestionCounter(props: OakLessonReviewItemProps) {
One more code style thing. I prefer arrow functions whenever possible. I meant to enforce this in the linter but never got round to it. I don't want these to creep in too much.

2024-01-30 14:58 UTC, kimon-satan approved these changes
Put a couple more tidy up points but have approved. Could you please do what James asked in his comment and re-request a review from him.

2024-01-30 14:58 UTC, kimon-satan commented on src/components/integrated/OakLessonReviewItem/OakPupilLessonReviewItem.tsx
> +type BaseOakLessonReviewItenProps = {
Typo

2024-01-30 14:58 UTC, kimon-satan commented on src/components/integrated/OakLessonReviewItem/OakPupilLessonReviewItem.tsx
> +  const map = new Map();
Can you give this a better name please

2024-01-30 14:58 UTC, kimon-satan commented on src/components/integrated/OakLessonReviewItem/OakPupilLessonReviewItem.tsx
> +type VideoSectionProps = {
These two prop types could be combined

2024-01-31 08:53 UTC, merged